Make detail::ElementProxy's copy ctor explicitly defaulted
Summary:
I'm working on getting RTC's Android stack to build with Clang 10; I uncovered
the following build error:

```
fbandroid/libraries/fbjni/cxx/fbjni/detail/CoreClasses.h:376:17: error: definition of implicit
copy constructor for 'ElementProxy<facebook::jni::JArrayClass<_jstring *> >' is deprecated
because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  ElementProxy& operator=(const ElementProxy& o);
                ^
fbandroid/libraries/fbjni/cxx/fbjni/detail/CoreClasses-inl.h:420:10: note: in implicit copy
constructor for 'facebook::jni::detail::ElementProxy<facebook::jni::JArrayClass<_jstring *> >'
first required here
  return detail::ElementProxy<JArrayClass<T>>(this, index);
         ^
xplat/perflogger/jniperflogger/QuickPerformanceLoggerJNI.cc:126:17: note: in instantiation of
member function 'facebook::jni::JArrayClass<_jstring *>::operator[]' requested here
        (*jData)[i] = jni::make_jstring(v.value.toString());
                ^
```

I believe the existing default copy constructor is correct, so I've just added
`ElementProxy(const ElementProxy&) noexcept = default;` to the class declaration.

Reviewed By: smeenai

Differential Revision: D19981031

fbshipit-source-id: 09b85dcc767c576657e79a43c54e947419a8b90c