fix lexing for flow typeof annotations
Summary:
Original Author: noahlemen@meta.com
Original Git: fec1e94f0d6df0ea99eb3b25c2a9106f39489367

noticed a bug introduced by D44099358: types like `A<B<typeof a>>` or `A<B<typeof a.a>>` would fail.

example:
```
error: '>' expected at end of type parameters
type T = A<B<typeof a>>;
            ~~~~~~~~~^
```

upon debugging, i noticed the following token was being lexed as `>>` instead of `>`, suggesting that we were using an incorrect GrammerContext. updates calls to `advance` here with `JSLexer::GrammarContext::Type`

Original Reviewed By: avp

Original Revision: D44917959

Reviewed By: neildhar

Differential Revision: D47690097

fbshipit-source-id: ed1fd13b724e89fc15e9e345996ca1ab16d3efb8