Add missing cstdint includes
Summary:
Original Author: theop@flowtr.dev
Original Git: 1753fa24132f0b6bc9ccf70fd465cb518a1eeddd

I added the missing <cstdint> includes to fix build errors when using uint*_t with clang 16. I also added .cache to gitignore so I don't acidentally commit the clangd LSP cache directory.

The errors that this PR fixes look like this:
```
          ^
/home/theo/dev/hermes/public/hermes/Public/../../hermes/Public/DebuggerTypes.h:40:11: error: unknown type name 'uint64_t'
constexpr uint64_t kInvalidBreakpoint = 0;
```

Original Reviewed By: avp

Original Revision: D47271899

Reviewed By: neildhar

Differential Revision: D47690637

fbshipit-source-id: 6a19a6934fca7705795017985c1e9bfba83f346e