Prevent Fuzzilli from generating classes during mutation
Summary:
Original Author: edq@fb.com
Original Git: c7b129f146686e18301f9e2ad84eb69d922b9632

Hermes currently does not support [class definitions](https://github.com/facebook/hermes/blob/main/doc/Features.md?plain=1#L44), so let's prevent `ClassGenerator` from being selected by the `CodeGenMutator`

```test.js
class Test {

}
```

```./hermes test.js
error: invalid statement encountered.
class Test {
^~~~~~~~~~~~
Emitted 1 errors. exiting.
```

Original Revision: D39083831

Reviewed By: neildhar

Differential Revision: D41240794

fbshipit-source-id: fc3228e4ea3e5b4dde5f60ea4b832bce48d0f2e1