Fix intl build
Summary:
Original Author: dsc@meta.com
Original Git: d3e9919688d12949e2a90cae58fe6efb7927124a

Build is failing due to:
```
stderr: xplat/hermes/lib/VM/JSLib/Intl.cpp:280:55: error: missing field 'flags' initializer [-Werror,-Wmissing-field-initializers]
    {u"dayPeriod", platform_intl::Option::Kind::String},
```

This line is brought in via GitHub Pull Request: D45185307

Original Reviewed By: neildhar

Original Revision: D46750063

Reviewed By: neildhar

Differential Revision: D47690534

fbshipit-source-id: 6a248df59a54d442cdef24f3f97960c0ddcd1b55