Increase stack size for worker (runtime) thread
Summary:
Original Author: dsc@meta.com
Original Git: fca284d3344af616e77220321f418e680074888d
Original Reviewed By: mattbfb
Original Revision: D53145701

Running AsyncDebuggerAPITest with ASAN enabled causes a bunch of "call
stack size exceeded" errors. Fixing this by switching to use pthread
and set the stack size of the runtime thread to be the same as the main
test runner thread. The runtime thread can be thought of as
HermesRuntime's main thread and needs more stack space.

```
******************** TEST 'Hermes-Unit :: API/./APITests/AsyncDebuggerAPITest.NoDebuggerEventCallbackTest' FAILED ********************
Note: Google Test filter = AsyncDebuggerAPITest.NoDebuggerEventCallbackTest
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from AsyncDebuggerAPITest
[ RUN      ] AsyncDebuggerAPITest.NoDebuggerEventCallbackTest
libc++abi: terminating due to uncaught exception of type facebook::jsi::JSError: Maximum call stack size exceeded (native stack depth)
RangeError: Maximum call stack size exceeded (native stack depth)
```

Reviewed By: mattbfb

Differential Revision: D56482770

fbshipit-source-id: 7249c2a980c06067c2d3ff290d6aefffc85dde6b