include the flags in the invalid flags msg
Summary:
This diff include the actual flags in the error message of initializing
a RegExp that is invalid because of its invalid flags.

Currently, only V8 included it:

```
λ eshost regexp-invalid.js
#### Hermes
SyntaxError: Invalid flags passed to RegExp

#### JavaScriptCore
SyntaxError: Invalid flags supplied to RegExp constructor.

#### SpiderMonkey
SyntaxError: invalid regular expression flag n

#### V8
SyntaxError: Invalid flags supplied to RegExp constructor 'undefined'
```

Reviewed By: avp

Differential Revision: D22633566

fbshipit-source-id: 1d0068be3abdfb8d689d7433a4d9e12fbac54c09